application: ilw-finder
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /data/.*
  static_dir: data
  application_readable: true

- url: /test/.*
  script: src.backend.main

- url: /updatedb/.*
  script: src.backend.main

- url: /get/.*
  script: src.db.fetch.Main

- url: /.*
  script: src.index.app

libraries:
- name: webapp2
  version: latest
