application: ilw-finder
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:

- url: /db-datasets
  static_dir: db-datasets
  application_readable: true

- url: /db-nat-neigh
  static_dir: db-nat-neigh
  application_readable: true

- url: /.*
  script: index.app

libraries:
- name: webapp2
  version: latest
