application: ilw-finder
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /.*
  script: index.app

- url: /db-datasets
  static_dir: datasets
  application_readable: true

- url: /db-nat-neigh
  static_dir: natural-neighbourhoods
  application_readable: true